force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Article Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry Id</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <label>Item Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Enquiry_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sofa: 1 Seater</fullName>
            </value>
            <value>
                <fullName>Sofa: 2 Seater</fullName>
            </value>
            <value>
                <fullName>Sofa: 3 Seater</fullName>
            </value>
            <value>
                <fullName>Centre Table</fullName>
            </value>
            <value>
                <fullName>Side Table</fullName>
            </value>
            <value>
                <fullName>Dining table - 4 Seater</fullName>
            </value>
            <value>
                <fullName>Dining table - 8 Seater</fullName>
            </value>
            <value>
                <fullName>Dining Chair</fullName>
            </value>
            <value>
                <fullName>Table</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Single Cot</fullName>
            </value>
            <value>
                <fullName>Single Mattress</fullName>
            </value>
            <value>
                <fullName>Double Cot, D/ ND</fullName>
            </value>
            <value>
                <fullName>Double Mattress</fullName>
            </value>
            <value>
                <fullName>Baby Cot</fullName>
            </value>
            <value>
                <fullName>Deewan</fullName>
            </value>
            <value>
                <fullName>Dressing table</fullName>
            </value>
            <value>
                <fullName>Small Cupboard</fullName>
            </value>
            <value>
                <fullName>Large Cupboard (Almirah)</fullName>
            </value>
            <value>
                <fullName>Show case - 5 Feet</fullName>
            </value>
            <value>
                <fullName>Book Rack</fullName>
            </value>
            <value>
                <fullName>Shoe Rack</fullName>
            </value>
            <value>
                <fullName>Side Board</fullName>
            </value>
            <value>
                <fullName>Chest of Draw</fullName>
            </value>
            <value>
                <fullName>Wooden Chest</fullName>
            </value>
            <value>
                <fullName>TV - Portable</fullName>
            </value>
            <value>
                <fullName>TV - 21&quot;</fullName>
            </value>
            <value>
                <fullName>TV - 29&quot;</fullName>
            </value>
            <value>
                <fullName>TV LCD / Plasma</fullName>
            </value>
            <value>
                <fullName>TV Trolley</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Enquiry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Line_1__c</fullName>
    <label>Destination Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Line_2__c</fullName>
    <label>Destination Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_City__c</fullName>
    <label>Destination City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_Floor__c.field-meta.xml
<CustomField>
    <fullName>Destination_Floor__c</fullName>
    <label>Destination Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ground Floor</fullName>
            </value>
            <value>
                <fullName>1st Floor</fullName>
            </value>
            <value>
                <fullName>2nd Floor</fullName>
            </value>
            <value>
                <fullName>3rd Floor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Destination_Postal_Code__c</fullName>
    <label>Destination Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_State__c.field-meta.xml
<CustomField>
    <fullName>Destination_State__c</fullName>
    <label>Destination State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Is_Lift_Available_at_Destination__c.field-meta.xml
<CustomField>
    <fullName>Is_Lift_Available_at_Destination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lift Available at Destination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Is_Lift_Available_at_Origin__c.field-meta.xml
<CustomField>
    <fullName>Is_Lift_Available_at_Origin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lift Available at Origin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Line_1__c</fullName>
    <label>Origin Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Line_2__c</fullName>
    <label>Origin Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_City__c.field-meta.xml
<CustomField>
    <fullName>Origin_City__c</fullName>
    <label>Origin City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_Floor__c.field-meta.xml
<CustomField>
    <fullName>Origin_Floor__c</fullName>
    <label>Origin Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ground Floor</fullName>
            </value>
            <value>
                <fullName>1st Floor</fullName>
            </value>
            <value>
                <fullName>2nd Floor</fullName>
            </value>
            <value>
                <fullName>3rd Floor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Origin_Postal_Code__c</fullName>
    <label>Origin Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_State__c.field-meta.xml
<CustomField>
    <fullName>Origin_State__c</fullName>
    <label>Origin State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Preferred_Date_of_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Delivery__c</fullName>
    <label>Preferred Date of Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Preferred_Date_of_Moving__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Moving__c</fullName>
    <label>Preferred Date of Moving</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Preferred_Date_of_Packing__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Packing__c</fullName>
    <label>Preferred Date of Packing</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquirys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Storage_Required__c.field-meta.xml
<CustomField>
    <fullName>Storage_Required__c</fullName>
    <label>Storage Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries(User Name)</relationshipLabel>
    <relationshipName>Enquiries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SurveySheetNew.cls
public with sharing class SurveySheetNew {
    public Enquiry__c enq {get;set;}
    public Boolean isArtPresent {get;set; }
    public Boolean isOthArtPresent {get;set; }
    public Boolean isAnyArtPresent {get;set; }
    public integer artCnt {get;set; }
    public integer othArtCnt {get;set; }
    public Decimal artTotalInsVal {get;set;}
    public Decimal othArtTotalInsVal {get;set;}
    public Decimal grandTotalInsVal {get;set;}
    public SurveySheetNew(ApexPages.StandardController stdController) {      
      isArtPresent = false;
      isOthArtPresent = false;
      isAnyArtPresent = false;
      artCnt =0;  
      othArtCnt = 0;  
      artTotalInsVal=0;
      othArtTotalInsVal=0;
      grandTotalInsVal =0;
      enq=[Select 
           Preferred_Date_of_Delivery__c, 
           Preferred_Date_of_Packing__c,
           Preferred_Date_of_Moving__c,
           Origin_City__c,
           Origin_Address_Line_1__c,Storage_Required__c,
           Origin_Address_Line_2__c,
           Origin_Postal_Code__c,
           Origin_State__c,
           Is_Lift_Available_at_Origin__c,
           Origin_Floor__c,
           Destination_City__c,
           Destination_Address_Line_1__c,            
           Destination_Address_Line_2__c,
           Destination_State__c,
           Destination_Postal_Code__c,
           Is_Lift_Available_at_Destination__c,
         	Destination_Floor__c,
           Company_Name__r.Name,
           User_Name__r.Name,  
           Primary_Contact__r.Email,
           Primary_Contact__r.Phone,  Name,           
           (select Item_Name__c,Quantity__c, Insurance_Value__c,Other_Article__c from Articles__r) 
           	from Enquiry__c where id=:ApexPages.currentPage().getParameters().get('id')];  
        	for(Article__c art:enq.Articles__r){
            	if(!art.Other_Article__c){
                	artTotalInsVal += art.Insurance_Value__c;   
                    artCnt++;
            	}
                else{
                    othArtTotalInsVal += art.Insurance_Value__c;
                    othArtCnt++;
                }                
        	}
        	grandTotalInsVal = artTotalInsVal + othArtTotalInsVal;
        	if(artCnt>0){
            	isArtPresent = true;
      		}
        	if(othArtCnt>0){
            	isOthArtPresent = true;
        	}
        	if(artCnt>0 || othArtCnt>0){
            	isAnyArtPresent = true;
        	}        	
  }
}