force-app/main/default/objects/Article__c/Article__c.object-meta.xml
<CustomObject>
    <label>Article</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Article Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Article__c/fields/Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry Id</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Articles</relationshipLabel>
    <relationshipName>Articles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Article__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <label>Item Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Enquiry_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sofa: 1 Seater</fullName>
            </value>
            <value>
                <fullName>Sofa: 2 Seater</fullName>
            </value>
            <value>
                <fullName>Sofa: 3 Seater</fullName>
            </value>
            <value>
                <fullName>Centre Table</fullName>
            </value>
            <value>
                <fullName>Side Table</fullName>
            </value>
            <value>
                <fullName>Dining table - 4 Seater</fullName>
            </value>
            <value>
                <fullName>Dining table - 8 Seater</fullName>
            </value>
            <value>
                <fullName>Dining Chair</fullName>
            </value>
            <value>
                <fullName>Table</fullName>
            </value>
            <value>
                <fullName>Chair</fullName>
            </value>
            <value>
                <fullName>Single Cot</fullName>
            </value>
            <value>
                <fullName>Single Mattress</fullName>
            </value>
            <value>
                <fullName>Double Cot, D/ ND</fullName>
            </value>
            <value>
                <fullName>Double Mattress</fullName>
            </value>
            <value>
                <fullName>Baby Cot</fullName>
            </value>
            <value>
                <fullName>Deewan</fullName>
            </value>
            <value>
                <fullName>Dressing table</fullName>
            </value>
            <value>
                <fullName>Small Cupboard</fullName>
            </value>
            <value>
                <fullName>Large Cupboard (Almirah)</fullName>
            </value>
            <value>
                <fullName>Show case - 5 Feet</fullName>
            </value>
            <value>
                <fullName>Book Rack</fullName>
            </value>
            <value>
                <fullName>Shoe Rack</fullName>
            </value>
            <value>
                <fullName>Side Board</fullName>
            </value>
            <value>
                <fullName>Chest of Draw</fullName>
            </value>
            <value>
                <fullName>Wooden Chest</fullName>
            </value>
            <value>
                <fullName>TV - Portable</fullName>
            </value>
            <value>
                <fullName>TV - 21&quot;</fullName>
            </value>
            <value>
                <fullName>TV - 29&quot;</fullName>
            </value>
            <value>
                <fullName>TV LCD / Plasma</fullName>
            </value>
            <value>
                <fullName>TV Trolley</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Enquiry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Enquiry_Type__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Type__c</fullName>
    <label>Enquiry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Household Goods</fullName>
            </value>
            <value>
                <fullName>Office Relocations</fullName>
            </value>
            <value>
                <fullName>Global Mobility Services</fullName>
            </value>
            <value>
                <fullName>Corporate &amp; Residential Leasing</fullName>
            </value>
            <value>
                <fullName>Design &amp; Build</fullName>
            </value>
            <value>
                <fullName>Fine-Art Logistic</fullName>
            </value>
            <value>
                <fullName>Information Management</fullName>
            </value>
            <value>
                <fullName>Door To Door</fullName>
            </value>
            <value>
                <fullName>Door To Port</fullName>
            </value>
            <value>
                <fullName>Port To Door</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ArticleControllerTest.cls
@isTest
public class ArticleControllerTest {
    @isTest    
    static void method1(){ 
        User crmUser = TestDataFactory.createUser(false,'CRM',30);
        insert crmUser;
        User newCrmUser = TestDataFactory.createUser(false,'CRM',11);
        insert newCrmUser;
        User invoiceUser = TestDataFactory.createUser(false,'CRM',31);
        insert invoiceUser;
        User opsUser = TestDataFactory.createUser(false,'Operation',32);
        insert opsUser;
        Account acc = TestDataFactory.createRegisteredAccount(false,'RSI Limited', crmUser.Id);
        insert acc;
        Contact con = TestDataFactory.createContact(false, 'Gaurav','Kumar',acc.Id);
        insert con;
        Enquiry__c enq = TestDataFactory.createEnquiry(false, acc.Id, con.Id, crmUser.Id, 'Domestic Enquiry');
        insert enq;
		Article__c art = TestDataFactory.createArticle(false,enq.id,'Table',10,10,2000);
        insert art;        
                
        Account a = [Select CRM_User__c, Name from Account where Id =: acc.Id];
        a.CRM_User__c = newCrmUser.Id;
        update a;
        
        ArticleController.getArticleList(art.Enquiry_Id__c, enq.Enquiry_Type__c);
        Article__c newArt = TestDataFactory.createArticle(false,enq.id,'Chair',20,10,2000);
        ArticleController.saveAction(newArt);
        
        List<articleWrapper> artWrapList = new List<articleWrapper>();
        List<Article__c>articles =  new List<Article__c>();
        articles.add(art);
        for(Article__c article : articles){
            articleWrapper artWarp  = new articleWrapper();
            artWarp.itemName = article.Item_Name__c;
            artWarp.Id = article.Id;
            artWarp.quantity = (Integer)article.Quantity__c;
            artWarp.unitVolume = (Integer)article.Unit_Volume__c;
            artWarp.insuranceValue = article.Insurance_Value__c;
            artWarp.enqId = article.Enquiry_Id__c;
            artWrapList.add(artWarp);
        }
        String jsonResponse = JSON.serialize(artWrapList);
        ArticleController.upsertArticle(jsonResponse);
    }  
    
    @isTest
    static void method2(){ 
        Account acc = TestDataFactory.createAccount(false,'RSI Limited');
        insert acc;
        Contact con = TestDataFactory.createContact(false, 'Gaurav','Kumar',acc.Id);
        insert con;
        User crmUser = TestDataFactory.createUser(false,'CRM',34);
        insert crmUser;
        User invoiceUser = TestDataFactory.createUser(false,'CRM',35);
        insert invoiceUser;
        User opsUser = TestDataFactory.createUser(false,'Operation',36);
        insert opsUser;
        Enquiry__c enq = TestDataFactory.createEnquiry(false, acc.Id, con.Id, crmUser.Id, 'Domestic Enquiry');
        insert enq;
        Article__c art = TestDataFactory.createArticle(false,enq.id,'Table',10,10,2000);
        insert art; 
        ArticleController.getArticleList(art.id,enq.Enquiry_Type__c);
        ArticleController.deleteArticle(art);
        
    }
    
    @isTest
    static void manageUpsertArticle(){
        Account acc = TestDataFactory.createAccount(false,'RSI Limited');
        insert acc;
        Contact con = TestDataFactory.createContact(false, 'Gaurav','Kumar',acc.Id);
        insert con;
        User crmUser = TestDataFactory.createUser(false,'CRM',37);
        insert crmUser;
        User invoiceUser = TestDataFactory.createUser(false,'CRM',38);
        insert invoiceUser;
        User opsUser = TestDataFactory.createUser(false,'Operation',39);
        insert opsUser;
        Enquiry__c enq = TestDataFactory.createEnquiry(false, acc.Id, con.Id, crmUser.Id, 'Domestic Enquiry', opsUser.Id, invoiceUser.Id);
        insert enq;
        List<articleWrapper> artWrapList = new List<articleWrapper>();
        articleWrapper artWarp  = new articleWrapper();
        artWarp.enqId = enq.Id;
        artWarp.itemName = 'Table';
        artWarp.quantity =20;
        artWarp.unitVolume = 10;
        artWarp.insuranceValue = 2000;
        artWrapList.add(artWarp);
        String jsonResponse = JSON.serialize(artWrapList);
        ArticleController.upsertArticle(jsonResponse);  
        
    }
    public class articleWrapper{
        @AuraEnabled
        public Id Id;
        @AuraEnabled
        public Id enqId;
        @AuraEnabled
        public String itemName;
        @AuraEnabled
        public Integer quantity;
        @AuraEnabled
        public Integer unitVolume;
        @AuraEnabled
        public Decimal insuranceValue;
    }
    
}