force-app/main/default/objects/Account/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Enquiry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Line_1__c</fullName>
    <label>Destination Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Destination_Address_Line_2__c</fullName>
    <label>Destination Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_City__c</fullName>
    <label>Destination City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Destination_Postal_Code__c</fullName>
    <label>Destination Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_State__c.field-meta.xml
<CustomField>
    <fullName>Destination_State__c</fullName>
    <label>Destination State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Estimated_Insurance_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Insurance_Value__c</fullName>
    <label>Estimated Insurance Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Line_1__c</fullName>
    <label>Origin Address Line 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Origin_Address_Line_2__c</fullName>
    <label>Origin Address Line 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_City__c.field-meta.xml
<CustomField>
    <fullName>Origin_City__c</fullName>
    <label>Origin City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Preferred_Date_of_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Delivery__c</fullName>
    <label>Preferred Date of Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquirys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries(User Name)</relationshipLabel>
    <relationshipName>Enquiries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Additional_Charge__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charge__c</fullName>
    <label>Additional Charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry Id</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GST__c.field-meta.xml
<CustomField>
    <fullName>GST__c</fullName>
    <label>GST</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Labour_Charges__c.field-meta.xml
<CustomField>
    <fullName>Labour_Charges__c</fullName>
    <label>Labour Charges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EnqNo_Qte_Office_Cor_MrAdminName.cls
public class EnqNo_Qte_Office_Cor_MrAdminName {
	public Account account {get;set;}
    public Quote__c qte {get;set;}
    public Decimal TotCost {get; set;}
    public Decimal GTotCost {get; set;}
    public Decimal GSTVal {get; set;}
	public Decimal AddCharges {get; set;}
    public Decimal LbrCharges {get; set;}
    public Decimal InsCov {get; set;}
    public  String Salutation {get;set;}
    public  String nameSal {get;set;}
    
    Public boolean valueExsist {get;set;}
    public EnqNo_Qte_Office_Cor_MrAdminName(ApexPages.StandardController stdController) {   		   
        TotCost = 0;
        GSTVal = 0;
        GTotCost=0;
		AddCharges = 0; 
        LbrCharges = 0;
        InsCov = 0;
        Salutation='';
        nameSal='';
       	qte=[Select Enquiry_Id__c,
            Enquiry_Id__r.Preferred_Date_of_Delivery__c, 
            Enquiry_Id__r.Origin_City__c,Enquiry_Id__r.Name,Enquiry_Id__r.Primary_Contact__r.Name,
            Enquiry_Id__r.Destination_City__c,
            Enquiry_Id__r.Destination_Address_Line_1__c,
            Enquiry_Id__r.Company_Name__r.Name,
            Enquiry_Id__r.Destination_Address_Line_2__c,
            Enquiry_Id__r.Destination_State__c,Enquiry_Id__r.Primary_Contact__r.Salutation,
            Enquiry_Id__r.Destination_Postal_Code__c,
            Enquiry_Id__r.Origin_Address_Line_1__c,
            Enquiry_Id__r.Origin_Address_Line_2__c,
            Enquiry_Id__r.User_Name__r.Name,Enquiry_Id__r.Mode__c,Enquiry_Id__r.Estimated_Insurance_Value__c,
            GST__c,Total_Cost__c,Labour_Charges__c,Insurance_Premium_Percentage__c,Additional_Charge__c,Enquiry_Id__r.Quote_Description__c, Margin__c
      		from Quote__c where id=:ApexPages.currentPage().getParameters().get('id')];
		
        if(qte.Enquiry_Id__r.Primary_Contact__r.Salutation.Contains('Ms.') ||qte.Enquiry_Id__r.Primary_Contact__r.Salutation.Contains('Mrs.') ){
            System.debug('++++++++++'+qte.Enquiry_Id__r.Primary_Contact__r.Salutation);
            Salutation='Mam';
            nameSal='Ms.';
        }
        if(qte.Enquiry_Id__r.Primary_Contact__r.Salutation.Contains('Mr.')){
            System.debug('++++++++++'+qte.Enquiry_Id__r.Primary_Contact__r.Salutation);
            Salutation='Sir';
            nameSal='Mr.';
        }
        Decimal Margin = 0;
        if(qte.Margin__c != null){
            Margin =qte.Margin__c;
        }
        if(qte.Total_Cost__c != null){
            TotCost =qte.Total_Cost__c;
        }
        TotCost += Margin;
       	 if(qte.GST__c != null && qte.GST__c=='18%'){
            
            GSTVal=(18*(TotCost+InsCov)/100);
          
        } 
        if(qte.GST__c != null && qte.GST__c=='5%'){
            
            GSTVal=(5*(TotCost+InsCov)/100);
       } 
        if(qte.GST__c != null && qte.GST__c=='12%'){
            
            GSTVal=(12*(TotCost+InsCov)/100);
 } 
        if(qte.GST__c != null && qte.GST__c=='0%'){
            
            GSTVal=(0*(TotCost+InsCov)/100);
            } 
        if(qte.Additional_Charge__c != null){
            AddCharges =qte.Additional_Charge__c;
        }
        if(qte.Labour_Charges__c != null){
            LbrCharges =qte.Labour_Charges__c;
        }
        if(qte.Insurance_Premium_Percentage__c > 0){
            InsCov = qte.Insurance_Premium_Percentage__c * (qte.Enquiry_Id__r.Estimated_Insurance_Value__c / 100) ;
            
        }       
        GTotCost = TotCost + GSTVal + InsCov + LbrCharges + AddCharges;    
  }
}