force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Enquiry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_City__c</fullName>
    <label>Destination City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_City__c.field-meta.xml
<CustomField>
    <fullName>Origin_City__c</fullName>
    <label>Origin City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Preferred_Date_of_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Delivery__c</fullName>
    <label>Preferred Date of Delivery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Preferred_Date_of_Moving__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Moving__c</fullName>
    <label>Preferred Date of Moving</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Preferred_Date_of_Packing__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Packing__c</fullName>
    <label>Preferred Date of Packing</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquirys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries(User Name)</relationshipLabel>
    <relationshipName>Enquiries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Process__c/Job_Process__c.object-meta.xml
<CustomObject>
    <label>Job Process</label>
    <nameField>
        <displayFormat>JP-{0000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Process__c/fields/Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry Id</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Job Processes</relationshipLabel>
    <relationshipName>Job_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Relocation_HouseHoldGoods_CSD.cls
public class Relocation_HouseHoldGoods_CSD {
    public Job_Process__c qte {get;set;}    
    public  String Salutation {get;set;}
    public  String nameSal {get;set;}
    
    public Relocation_HouseHoldGoods_CSD(ApexPages.StandardController stdController) {        
        Salutation='';
        nameSal='';
        qte=[Select Enquiry_Id__c, Enquiry_Id__r.ENQ_ID__c,
             Enquiry_Id__r.Preferred_Date_of_Packing__c, 
             Enquiry_Id__r.Preferred_Date_of_Moving__c,
             Enquiry_Id__r.Preferred_Date_of_Delivery__c,
             Enquiry_Id__r.Origin_City__c,Enquiry_Id__r.Name,Enquiry_Id__r.Primary_Contact__r.Name,
             Enquiry_Id__r.Destination_City__c,Enquiry_Id__r.Primary_Contact__r.Salutation,             
             Enquiry_Id__r.Company_Name__r.Name,             
             Enquiry_Id__r.User_Name__r.Name,
             CSD_User__r.Name
             from Job_Process__c where id=:ApexPages.currentPage().getParameters().get('id')];
        
        if(qte.Enquiry_Id__r.Primary_Contact__r.Salutation.Contains('Ms.') ||
           qte.Enquiry_Id__r.Primary_Contact__r.Salutation.Contains('Mrs.') ){
               Salutation='Mam';
               nameSal='Ms.';
           }
        if(qte.Enquiry_Id__r.Primary_Contact__r.Salutation.Contains('Mr.')){
            Salutation='Sir';
            nameSal='Mr.';
        }          
    }
}