force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Enquiry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Enquiry_Type__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Type__c</fullName>
    <label>Enquiry Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Household Goods</fullName>
            </value>
            <value>
                <fullName>Office Relocations</fullName>
            </value>
            <value>
                <fullName>Global Mobility Services</fullName>
            </value>
            <value>
                <fullName>Corporate &amp; Residential Leasing</fullName>
            </value>
            <value>
                <fullName>Design &amp; Build</fullName>
            </value>
            <value>
                <fullName>Fine-Art Logistic</fullName>
            </value>
            <value>
                <fullName>Information Management</fullName>
            </value>
            <value>
                <fullName>Door To Door</fullName>
            </value>
            <value>
                <fullName>Door To Port</fullName>
            </value>
            <value>
                <fullName>Port To Door</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry Id</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PDFHandlerController.cls
public with sharing class PDFHandlerController {

    public boolean renderpage{get;set;}
    public string Pagename {get;set;}
	string recordid;
    public PDFHandlerController(ApexPages.StandardController stdController) {
        renderpage=false;
        Pagename='Placeholder';
        recordid=ApexPages.currentPage().getParameters().get('id') ;
        if(string.isNotBlank(recordid)){
            RenderPage();
        }
    }

    void RenderPage(){
        list<Quote__c>lstQuote=[SELECT Id, Enquiry_Id__r.Enquiry_type__c FROM Quote__c where id=:recordid];
        if(lstQuote.size()>0){
            string getEnquirytype=lstQuote[0].Enquiry_Id__r.Enquiry_type__c;
            list<PDFPageMapping__mdt> lstpagemapping=[SELECT Id, Pagename__c, SelectOption__c FROM PDFPageMapping__mdt where SelectOption__c =:getEnquirytype];
            if(lstpagemapping.size()>0){
                Pagename=lstpagemapping[0].Pagename__c;
                renderpage=true;
            }
        }
    }
}