force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Enquiry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Destination_City__c</fullName>
    <label>Destination City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Origin_City__c.field-meta.xml
<CustomField>
    <fullName>Origin_City__c</fullName>
    <label>Origin City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquirys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Enquiry_Id__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry Id</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/practiseHtml.cls
public with sharing class practiseHtml {
    public Quote__c qte {get;set;}
    

    public practiseHtml(ApexPages.StandardController stdController) {
      system.debug(ApexPages.currentPage().getParameters().get('id'));   
      
       qte=[Select Enquiry_Id__c,Enquiry_Id__r.Primary_Contact__c, Enquiry_Id__r.Origin_City__c, Enquiry_Id__r.Destination_City__c 
      from Quote__c where id=:ApexPages.currentPage().getParameters().get('id')];

 
      
  }
  
}