force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Enquiry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pre-Move Survey Planning</fullName>
            </value>
            <value>
                <fullName>Pre Move Survey Allocation &amp; Scheduling</fullName>
            </value>
            <value>
                <fullName>Pre Move Survey Report Submission</fullName>
            </value>
            <value>
                <fullName>Pre Move Survey Verification &amp; Feedback from Client</fullName>
            </value>
            <value>
                <fullName>Operational Costing Report Submission</fullName>
            </value>
            <value>
                <fullName>Pre Move Survey Report &amp; Project Costing Analysis</fullName>
            </value>
            <value>
                <fullName>Quote Preparation</fullName>
            </value>
            <value>
                <fullName>Quote Submission</fullName>
            </value>
            <value>
                <fullName>Sales Follow Up on Quote submitted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TATDateTimeUpdateTest.cls
@isTest
public class TATDateTimeUpdateTest {
    @isTest static void testTATDateTimeInsertAndUpdate(){  
        Account acc = TestDataFactory.createAccount(false,'RSI Limited');
        insert acc;
        Contact con = TestDataFactory.createContact(false, 'Gaurav','Kumar',acc.Id);
        insert con;
        User crmUser = TestDataFactory.createUser(false,'CRM',1);
        insert crmUser;
        User opsUser = TestDataFactory.createUser(false,'Operation',2);
        insert opsUser;
        User invoiceUser = TestDataFactory.createUser(false,'CRM',3);
        insert invoiceUser;
        Enquiry__c enq = TestDataFactory.createEnquiry(false, acc.Id, con.Id,crmUser.Id, 'Domestic Enquiry', opsUser.Id, invoiceUser.Id);
        insert enq;
        Quote__c quo = TestDataFactory.createQuote(false, enq.Id);   
        insert quo;   
        Enquiry__c enqToUpdate = [Select Id,Stage__c,Survey_Date_Time__c,Survey_Acknowledgement__c,Survey_Type__c From Enquiry__c where Id =: enq.Id];
        enqToUpdate.Stage__c = 'Quote Submission';
        enqToUpdate.Survey_Date_Time__c = system.now();  
        update enqToUpdate;
    } 
    @isTest static void testTATDateTimeUpdate(){
    Account acc = TestDataFactory.createAccount(false,'RSI Limited');
        insert acc;
        Contact con = TestDataFactory.createContact(false, 'Gaurav','Kumar',acc.Id);
        insert con;
        User crmUser = TestDataFactory.createUser(false,'CRM',4);
        insert crmUser;
        User opsUser = TestDataFactory.createUser(false,'Operation',5);
        insert opsUser;
        User invoiceUser = TestDataFactory.createUser(false,'CRM',6);
        insert invoiceUser;
        Enquiry__c enq = TestDataFactory.createEnquiry(false, acc.Id, con.Id,crmUser.Id, 'Domestic Enquiry', opsUser.Id, invoiceUser.Id);
        insert enq;
        Quote__c quo = TestDataFactory.createQuote(false, enq.Id);   
        insert quo;  
        Enquiry__c enqToUpdate = [Select Id,Stage__c,Survey_Date_Time__c,Survey_Acknowledgement__c,Survey_Type__c From Enquiry__c where Id =: enq.Id];
        enqToUpdate.Stage__c = 'Estimate Costing';
        enqToUpdate.Survey_Date_Time__c = system.now();  
        update enqToUpdate;    
    }
}